#!/bin/bash

path=$1
port=${2-10921}

[ $# -eq 0 -o $# -gt 2 ] && { echo "Usage: $0 dbpath [port]"; exit 1; }

mongod --dbpath $path --port $port --directoryperdb --fork --journal --logpath $path/log.log --nohttpinterface

