#!/usr/bin/env python

"""
This is an exact copy of the hyperopt-mongo-worker script found in the
*script* folder of hyperopt. We replicate it here in order to make simple-hp
self-contained w.r.t. user interactions.

Basically, the worker connects to the Mongo database in the given host:port
and evaluates points in the search space available in the *jobs* collection.

Hint: to allocate a specific GPU to compute these points, use
THEANO_FLAGS=device=gpuX ./hp-worker --mongo=host:port/simple-hp [OPTIONS]"


"""

import sys
import hyperopt.mongoexp
import logging
logging.basicConfig(
        stream=sys.stderr,
        level=logging.INFO)
sys.exit(hyperopt.mongoexp.main_worker())
